using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DeathWall : MonoBehaviour
{
    [SerializeField]
    private float Speed = 10.0F;
    private void OnTriggerEnter2D(Collider2D collider)
    {
        Character character = collider.GetComponent<Character>();
        if (character != null)
        {
            Destroy(character.gameObject);
        }
    }
    private void Update()
    {
        Vector3 direction = transform.right;
        transform.position = Vector3.MoveTowards(transform.position, 
        transform.position + direction, Speed * Time.deltaTime);
    }
}
